ENV http_proxy http://proxycentral.imasmallorca.net:8080
ENV HTTP_PROXY http://proxycentral.imasmallorca.net:8080
FROM jboss/wildfly
ADD target/node-info.war /opt/jboss/wildfly/standalone/deployments
